/* Jazon Staff Commission Calculator - fixed GAME_GIFT catalog (read-only extract).
   Sources: owner-catalog.json (156 FIXED_GAME_GIFT rows of 166 total)
            game-gift-price-manifest.v1.json (156 entries, authoritative customer prices)
   Manifest SHA-256: bfc7ff84b9d4d72e4f7d1e9e55e2b9ef94ab293d03b93e23d79f1297c945f355
   Excluded: 7 VIA_GAMEPASS rows, 3 DEFERRED rows. No UUIDs or confidential data.
   g=game, c=category, t=title, s=slug, r=Robux gift cost, p=customer price (centavos). */
var CATALOG = [
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Amber Aura",s:"plus-1-speed-monkey-escape-auras-amber-aura",r:19,p:899},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Bloodmoon Aura",s:"plus-1-speed-monkey-escape-auras-bloodmoon-aura",r:1499,p:67499},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Electric Aura",s:"plus-1-speed-monkey-escape-auras-electric-aura",r:2399,p:107999},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Fairy Aura",s:"plus-1-speed-monkey-escape-auras-fairy-aura",r:499,p:22499},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Ice Cold Aura",s:"plus-1-speed-monkey-escape-auras-ice-cold-aura",r:39,p:1799},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Lunar Aura",s:"plus-1-speed-monkey-escape-auras-lunar-aura",r:199,p:8999},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Nature Aura",s:"plus-1-speed-monkey-escape-auras-nature-aura",r:79,p:3599},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Rainbow Aura",s:"plus-1-speed-monkey-escape-auras-rainbow-aura",r:129,p:5899},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Sakura Aura",s:"plus-1-speed-monkey-escape-auras-sakura-aura",r:1799,p:80999},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Sparkle Aura",s:"plus-1-speed-monkey-escape-auras-sparkle-aura",r:299,p:13499},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Spectral Aura",s:"plus-1-speed-monkey-escape-auras-spectral-aura",r:799,p:35999},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Void Aura",s:"plus-1-speed-monkey-escape-auras-void-aura",r:2799,p:125999},
  {g:"+1 Speed Monkey Escape",c:"Auras",t:"Yin Yang Aura",s:"plus-1-speed-monkey-escape-auras-yin-yang-aura",r:1199,p:53999},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"Starter Pack [OP]",s:"plus-1-speed-monkey-escape-main-passes-starter-pack-op",r:9,p:499},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"VIP",s:"plus-1-speed-monkey-escape-main-passes-vip",r:99,p:4499},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"x100 Void Treadmill [OP]",s:"plus-1-speed-monkey-escape-main-passes-x100-void-treadmill-op",r:1599,p:71999},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"x1000 Celestia Treadmill [OP]",s:"plus-1-speed-monkey-escape-main-passes-x1000-celestia-treadmill-op",r:4999,p:224999},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"x2 Charms Shop Luck",s:"plus-1-speed-monkey-escape-main-passes-x2-charms-shop-luck",r:99,p:4499},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"x25 Galaxy Treadmill",s:"plus-1-speed-monkey-escape-main-passes-x25-galaxy-treadmill",r:719,p:32399},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"x3 Golden Treadmill",s:"plus-1-speed-monkey-escape-main-passes-x3-golden-treadmill",r:69,p:3199},
  {g:"+1 Speed Monkey Escape",c:"Main Passes",t:"x9 Diamond Treadmill",s:"plus-1-speed-monkey-escape-main-passes-x9-diamond-treadmill",r:239,p:10799},
  {g:"+1 Speed Monkey Escape",c:"Tails",t:"Bone Tail",s:"plus-1-speed-monkey-escape-tails-bone-tail",r:899,p:40499},
  {g:"+1 Speed Monkey Escape",c:"Tails",t:"Mecha Tail",s:"plus-1-speed-monkey-escape-tails-mecha-tail",r:1299,p:58499},
  {g:"+1 Speed Monkey Escape",c:"Tails",t:"Shadow Tail",s:"plus-1-speed-monkey-escape-tails-shadow-tail",r:349,p:15799},
  {g:"+1 Speed Monkey Escape",c:"Tails",t:"Toxic Tail",s:"plus-1-speed-monkey-escape-tails-toxic-tail",r:199,p:8999},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Bloodmoon Trail",s:"plus-1-speed-monkey-escape-trails-bloodmoon-trail",r:1499,p:67499},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Blue Trail",s:"plus-1-speed-monkey-escape-trails-blue-trail",r:39,p:1799},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Divine Trail",s:"plus-1-speed-monkey-escape-trails-divine-trail",r:299,p:13499},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Fairy Trail",s:"plus-1-speed-monkey-escape-trails-fairy-trail",r:499,p:22499},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Flash Trail",s:"plus-1-speed-monkey-escape-trails-flash-trail",r:2399,p:107999},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Galaxy Trail",s:"plus-1-speed-monkey-escape-trails-galaxy-trail",r:199,p:8999},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Green Trail",s:"plus-1-speed-monkey-escape-trails-green-trail",r:79,p:3599},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Rainbow Trail",s:"plus-1-speed-monkey-escape-trails-rainbow-trail",r:129,p:5899},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Red Trail",s:"plus-1-speed-monkey-escape-trails-red-trail",r:19,p:899},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Sakura Trail",s:"plus-1-speed-monkey-escape-trails-sakura-trail",r:1799,p:80999},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Spectral Trail",s:"plus-1-speed-monkey-escape-trails-spectral-trail",r:799,p:35999},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Void Trail",s:"plus-1-speed-monkey-escape-trails-void-trail",r:2799,p:125999},
  {g:"+1 Speed Monkey Escape",c:"Trails",t:"Yin Yang Trail",s:"plus-1-speed-monkey-escape-trails-yin-yang-trail",r:1199,p:53999},
  {g:"Animal Hospital (Anomaly)",c:"Animal Coins",t:"Huge Pack â€” 3,250 Animal Coins",s:"animal-hospital-anomaly-animal-coins-huge-pack-3-250-animal-coins",r:1590,p:71599},
  {g:"Animal Hospital (Anomaly)",c:"Animal Coins",t:"Large Pack â€” 1,500 Animal Coins",s:"animal-hospital-anomaly-animal-coins-large-pack-1-500-animal-coins",r:890,p:40099},
  {g:"Animal Hospital (Anomaly)",c:"Animal Coins",t:"Medium Pack â€” 500 Animal Coins",s:"animal-hospital-anomaly-animal-coins-medium-pack-500-animal-coins",r:380,p:17600},
  {g:"Animal Hospital (Anomaly)",c:"Animal Coins",t:"Small Pack â€” 100 Animal Coins",s:"animal-hospital-anomaly-animal-coins-small-pack-100-animal-coins",r:99,p:4499},
  {g:"Blox Fruits",c:"Fruit Skin Gifting",t:"1 Roll",s:"blox-fruits-fruit-skin-gifting-1-roll",r:199,p:8999},
  {g:"Blox Fruits",c:"Fruit Skin Gifting",t:"10 Rolls",s:"blox-fruits-fruit-skin-gifting-10-rolls",r:1699,p:76499},
  {g:"Blox Fruits",c:"Fruit Skin Gifting",t:"3 Rolls",s:"blox-fruits-fruit-skin-gifting-3-rolls",r:575,p:25899},
  {g:"Blox Fruits",c:"Gamepasses",t:"+1 Fruit Storage",s:"blox-fruits-gamepasses-plus-1-fruit-storage",r:400,p:18500},
  {g:"Blox Fruits",c:"Gamepasses",t:"2x Boss Drops",s:"blox-fruits-gamepasses-2x-boss-drops",r:350,p:15799},
  {g:"Blox Fruits",c:"Gamepasses",t:"2x Mastery",s:"blox-fruits-gamepasses-2x-mastery",r:450,p:20299},
  {g:"Blox Fruits",c:"Gamepasses",t:"2x Money",s:"blox-fruits-gamepasses-2x-money",r:450,p:20299},
  {g:"Blox Fruits",c:"Gamepasses",t:"Dark Blade",s:"blox-fruits-gamepasses-dark-blade",r:1200,p:55000},
  {g:"Blox Fruits",c:"Gamepasses",t:"Fast Boats",s:"blox-fruits-gamepasses-fast-boats",r:350,p:15799},
  {g:"Blox Fruits",c:"Gamepasses",t:"Fruit Notifier",s:"blox-fruits-gamepasses-fruit-notifier",r:2700,p:123000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Blade",s:"blox-fruits-permanent-fruits-blade",r:100,p:4700},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Blizzard",s:"blox-fruits-permanent-fruits-blizzard",r:2250,p:101300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Bomb",s:"blox-fruits-permanent-fruits-bomb",r:220,p:10100},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Buddha",s:"blox-fruits-permanent-fruits-buddha",r:1650,p:74300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Control",s:"blox-fruits-permanent-fruits-control",r:4000,p:182000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Creation",s:"blox-fruits-permanent-fruits-creation",r:1750,p:78800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Dark",s:"blox-fruits-permanent-fruits-dark",r:950,p:42800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Diamond",s:"blox-fruits-permanent-fruits-diamond",r:1000,p:45500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Dough",s:"blox-fruits-permanent-fruits-dough",r:2400,p:109500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Dragon",s:"blox-fruits-permanent-fruits-dragon",r:5000,p:227000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Eagle",s:"blox-fruits-permanent-fruits-eagle",r:975,p:43900},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Flame",s:"blox-fruits-permanent-fruits-flame",r:550,p:24800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Gas",s:"blox-fruits-permanent-fruits-gas",r:2500,p:114000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Ghost",s:"blox-fruits-permanent-fruits-ghost",r:1275,p:57400},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Gravity",s:"blox-fruits-permanent-fruits-gravity",r:2300,p:105000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Ice",s:"blox-fruits-permanent-fruits-ice",r:750,p:33800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Kitsune",s:"blox-fruits-permanent-fruits-kitsune",r:4000,p:182000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Light",s:"blox-fruits-permanent-fruits-light",r:1100,p:50000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Love",s:"blox-fruits-permanent-fruits-love",r:1700,p:77500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Magma",s:"blox-fruits-permanent-fruits-magma",r:1300,p:59500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Magnet",s:"blox-fruits-permanent-fruits-magnet",r:3500,p:159500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Mammoth",s:"blox-fruits-permanent-fruits-mammoth",r:2350,p:105800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Pain",s:"blox-fruits-permanent-fruits-pain",r:2200,p:100000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Phoenix",s:"blox-fruits-permanent-fruits-phoenix",r:2000,p:91000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Portal",s:"blox-fruits-permanent-fruits-portal",r:2000,p:91000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Quake",s:"blox-fruits-permanent-fruits-quake",r:1500,p:68500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Rocket",s:"blox-fruits-permanent-fruits-rocket",r:50,p:2300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Rubber",s:"blox-fruits-permanent-fruits-rubber",r:1200,p:55000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Rumble",s:"blox-fruits-permanent-fruits-rumble",r:2100,p:95500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Sand",s:"blox-fruits-permanent-fruits-sand",r:850,p:38300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Shadow",s:"blox-fruits-permanent-fruits-shadow",r:2425,p:109200},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Smoke",s:"blox-fruits-permanent-fruits-smoke",r:250,p:11300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Sound",s:"blox-fruits-permanent-fruits-sound",r:1900,p:86500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Spider",s:"blox-fruits-permanent-fruits-spider",r:1800,p:82000},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Spike",s:"blox-fruits-permanent-fruits-spike",r:380,p:17600},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Spin",s:"blox-fruits-permanent-fruits-spin",r:75,p:3400},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Spirit",s:"blox-fruits-permanent-fruits-spirit",r:2550,p:114800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Spring",s:"blox-fruits-permanent-fruits-spring",r:180,p:8300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Tiger",s:"blox-fruits-permanent-fruits-tiger",r:3000,p:136500},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"T-Rex",s:"blox-fruits-permanent-fruits-t-rex",r:2350,p:105800},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Venom",s:"blox-fruits-permanent-fruits-venom",r:2450,p:110300},
  {g:"Blox Fruits",c:"Permanent Fruits",t:"Yeti",s:"blox-fruits-permanent-fruits-yeti",r:3000,p:136500},
  {g:"Brookhaven",c:"Gamepasses",t:"Boat Pack",s:"brookhaven-gamepasses-boat-pack",r:299,p:13499},
  {g:"Brookhaven",c:"Gamepasses",t:"Disaster Pack",s:"brookhaven-gamepasses-disaster-pack",r:499,p:22499},
  {g:"Brookhaven",c:"Gamepasses",t:"Estates Unlocked",s:"brookhaven-gamepasses-estates-unlocked",r:799,p:35999},
  {g:"Brookhaven",c:"Gamepasses",t:"Faces Unlocked",s:"brookhaven-gamepasses-faces-unlocked",r:40,p:2000},
  {g:"Brookhaven",c:"Gamepasses",t:"Horse Upgrade",s:"brookhaven-gamepasses-horse-upgrade",r:99,p:4499},
  {g:"Brookhaven",c:"Gamepasses",t:"Land Unlocked",s:"brookhaven-gamepasses-land-unlocked",r:499,p:22499},
  {g:"Brookhaven",c:"Gamepasses",t:"Music Unlocked",s:"brookhaven-gamepasses-music-unlocked",r:199,p:8999},
  {g:"Brookhaven",c:"Gamepasses",t:"On Demand Fire",s:"brookhaven-gamepasses-on-demand-fire",r:50,p:2299},
  {g:"Brookhaven",c:"Gamepasses",t:"Penthouse",s:"brookhaven-gamepasses-penthouse",r:150,p:6799},
  {g:"Brookhaven",c:"Gamepasses",t:"Premium",s:"brookhaven-gamepasses-premium",r:275,p:12399},
  {g:"Brookhaven",c:"Gamepasses",t:"Speed Unlocked",s:"brookhaven-gamepasses-speed-unlocked",r:199,p:8999},
  {g:"Brookhaven",c:"Gamepasses",t:"Theme Pack",s:"brookhaven-gamepasses-theme-pack",r:299,p:13499},
  {g:"Brookhaven",c:"Gamepasses",t:"Vehicle Pack",s:"brookhaven-gamepasses-vehicle-pack",r:799,p:35999},
  {g:"Brookhaven",c:"Gamepasses",t:"Vehicle Upgrade",s:"brookhaven-gamepasses-vehicle-upgrade",r:30,p:1399},
  {g:"Brookhaven",c:"Gamepasses",t:"VIP",s:"brookhaven-gamepasses-vip",r:999,p:44999},
  {g:"Drag Drive",c:"Gamepasses",t:"2x Paycheck",s:"drag-drive-gamepasses-2x-paycheck",r:499,p:22500},
  {g:"Drag Drive",c:"Gamepasses",t:"Advance Paint Pass",s:"drag-drive-gamepasses-advance-paint-pass",r:59,p:3000},
  {g:"Drag Drive",c:"Gamepasses",t:"Boombox Radio",s:"drag-drive-gamepasses-boombox-radio",r:29,p:1500},
  {g:"Drag Drive",c:"Gamepasses",t:"Custom Plate Pass",s:"drag-drive-gamepasses-custom-plate-pass",r:79,p:4000},
  {g:"Drag Drive",c:"Gamepasses",t:"Dragspec Pass",s:"drag-drive-gamepasses-dragspec-pass",r:109,p:5000},
  {g:"Drag Drive",c:"Gamepasses",t:"Exclusive Rims",s:"drag-drive-gamepasses-exclusive-rims",r:79,p:4000},
  {g:"Drag Drive",c:"Gamepasses",t:"Luxury Pass",s:"drag-drive-gamepasses-luxury-pass",r:119,p:5500},
  {g:"Drag Drive",c:"Gamepasses",t:"Police Pass",s:"drag-drive-gamepasses-police-pass",r:149,p:7000},
  {g:"Drag Drive",c:"Gamepasses",t:"Premium Accessories",s:"drag-drive-gamepasses-premium-accessories",r:59,p:3000},
  {g:"Drag Drive",c:"Gamepasses",t:"Slot Limit Unlock Pass",s:"drag-drive-gamepasses-slot-limit-unlock-pass",r:89,p:4500},
  {g:"Drag Drive",c:"Gamepasses",t:"Suspension Pro Pass",s:"drag-drive-gamepasses-suspension-pro-pass",r:29,p:1500},
  {g:"Drag Drive",c:"RP",t:"1,000,000 RP",s:"drag-drive-rp-1-000-000-rp",r:9,p:500},
  {g:"Drag Drive",c:"RP",t:"10,000,000 RP",s:"drag-drive-rp-10-000-000-rp",r:35,p:1800},
  {g:"Drag Drive",c:"RP",t:"100,000,000 RP",s:"drag-drive-rp-100-000-000-rp",r:99,p:4500},
  {g:"Drag Drive",c:"RP",t:"5,000,000 RP",s:"drag-drive-rp-5-000-000-rp",r:18,p:1000},
  {g:"Drag Drive",c:"RP",t:"50,000,000 RP",s:"drag-drive-rp-50-000-000-rp",r:59,p:2900},
  {g:"Drag Drive",c:"RP",t:"500,000,000 RP",s:"drag-drive-rp-500-000-000-rp",r:399,p:18000},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Big Coop (3x Storage)",s:"grow-a-chicken-fighter-gamepasses-big-coop-3x-storage",r:199,p:8999},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Double Corn",s:"grow-a-chicken-fighter-gamepasses-double-corn",r:299,p:13499},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Double Money",s:"grow-a-chicken-fighter-gamepasses-double-money",r:299,p:13499},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Elevator VIP",s:"grow-a-chicken-fighter-gamepasses-elevator-vip",r:149,p:6799},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Everything x2",s:"grow-a-chicken-fighter-gamepasses-everything-x2",r:549,p:24799},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock 3",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-3",r:99,p:4499},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock 4",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-4",r:149,p:6799},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock 5",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-5",r:249,p:11299},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock 6",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-6",r:399,p:17999},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock 7",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-7",r:599,p:26999},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock 8",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-8",r:899,p:40499},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Fusion Lock Master (All Fusion Locks)",s:"grow-a-chicken-fighter-gamepasses-fusion-lock-master-all-fusion-locks",r:1199,p:53999},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"King of the Coop",s:"grow-a-chicken-fighter-gamepasses-king-of-the-coop",r:1499,p:67499},
  {g:"Grow a Chicken Fighter",c:"Gamepasses",t:"Speedy Sneakers",s:"grow-a-chicken-fighter-gamepasses-speedy-sneakers",r:149,p:6799},
  {g:"Jujutsu Shenanigans",c:"Gamepasses",t:"Awakening Outfits",s:"jujutsu-shenanigans-gamepasses-awakening-outfits",r:100,p:4700},
  {g:"Jujutsu Shenanigans",c:"Gamepasses",t:"Custom Kill Sound",s:"jujutsu-shenanigans-gamepasses-custom-kill-sound",r:100,p:4700},
  {g:"Jujutsu Shenanigans",c:"Gamepasses",t:"Early Access",s:"jujutsu-shenanigans-gamepasses-early-access",r:300,p:14000},
  {g:"Jujutsu Shenanigans",c:"Gamepasses",t:"More Build Saves",s:"jujutsu-shenanigans-gamepasses-more-build-saves",r:125,p:5699},
  {g:"Jujutsu Shenanigans",c:"Gamepasses",t:"More Emote Slots",s:"jujutsu-shenanigans-gamepasses-more-emote-slots",r:150,p:6799},
  {g:"Jujutsu Shenanigans",c:"Gamepasses",t:"Second Emote Page",s:"jujutsu-shenanigans-gamepasses-second-emote-page",r:175,p:7899},
  {g:"Rivals",c:"Bundles",t:"Classic Bundle",s:"rivals-bundles-classic-bundle",r:1149,p:51799},
  {g:"Rivals",c:"Bundles",t:"Energy Bundle",s:"rivals-bundles-energy-bundle",r:1299,p:58499},
  {g:"Rivals",c:"Bundles",t:"Exogun Bundle",s:"rivals-bundles-exogun-bundle",r:649,p:29299},
  {g:"Rivals",c:"Bundles",t:"Heavy Duty Bundle",s:"rivals-bundles-heavy-duty-bundle",r:1899,p:85499},
  {g:"Rivals",c:"Bundles",t:"Medkit Bundle",s:"rivals-bundles-medkit-bundle",r:249,p:11299},
  {g:"Rivals",c:"Bundles",t:"RPG Bundle",s:"rivals-bundles-rpg-bundle",r:124,p:5599},
  {g:"Rivals",c:"Bundles",t:"Standard Weapons Bundle",s:"rivals-bundles-standard-weapons-bundle",r:999,p:44999},
  {g:"Rivals",c:"Bundles",t:"Starter Bundle",s:"rivals-bundles-starter-bundle",r:49,p:2299},
  {g:"Rivals",c:"Skincase",t:"x1 Skincase",s:"rivals-skincase-x1-skincase",r:249,p:11299},
  {g:"Rivals",c:"Skincase",t:"x3 Skincase",s:"rivals-skincase-x3-skincase",r:724,p:32599}
];
